name: TelegramNotifications
version: 2.3.2
main: com.telegramnotifications.Main
api-version: 1.21

commands:
  telereload:
    description: Recarga la configuración de TelegramNotifications
    usage: /<command>
    permission: telegramnotifications.reload
    
permissions:
  telegramnotifications.reload:
    description: Permite recargar la configuración del plugin
    default: op
